import meshio
import numpy as np
import vtk
from vtk.util import numpy_support
import pandas as pd
import sys
import os
import matplotlib.pyplot as plt
from scipy.interpolate import CubicSpline
from scipy.signal import savgol_filter

# ==========================================
# 1. CONFIGURATION
# ==========================================
# --- INPUTS ---
CSV_FILE = "0D-volumes/circulation_reduced.csv"
BASE_NAME = "reduced"

plot_sol_img = f"{BASE_NAME}_vol.png"

# UPDATED: Use the new aligned mesh file generated by your Gmsh script
MESH_FILE = "/home/andrea/Scrivania/phd/dev/mesh-generation/torso/pvpython/temp_geometry.msh" 

# --- TIME RANGE ---
TIME_START = 78.4
TIME_END = 79.2

# --- GEOMETRY (Apex Location) ---
# CRITICAL UPDATE:
# Original Apex was at (0, 0, -60).
# Translation applied was (70.1286, 1351.41, 67.9257).
# New Z = -60 + 67.9257 = 7.9257
# New Apex = [70.1286, 1351.41, 7.9257]
#APEX_COORDS = np.array([-70.1286, -1351.41, -127.9257])

# --- OUTPUT SETTINGS ---
# "single": Saves 1 file with arrays 'displacement_000'...
# "multiple": Saves many files in a folder (BEST FOR ANIMATION)
SAVE_MODE = "single"  

OUTPUT_SINGLE_NAME = f"displacement_{BASE_NAME}.vtp"
OUTPUT_DIR_NAME = "prolate_displacement"

# ==========================================
# 2. DATA LOADING & PREPROCESSING
# ==========================================
print(f"--- Reading {CSV_FILE} ---")
df = pd.read_csv(CSV_FILE)

# Filter Time
df = df[(df['time'] >= TIME_START) & (df['time'] <= TIME_END)].copy()
if df.empty:
    print(f"Error: No data in range {TIME_START} - {TIME_END}")
    sys.exit(1)

# Extract Raw Data
raw_times = df['time'].values.copy()
raw_volumes = df['VLV'].values.copy() 

print(f"Time steps found: {len(raw_times)}")

# Initialize output variables
times = raw_times
volumes = df['VLV'].values.copy() # Using smooth volume
# if volumes[-1] != volumes[0]:
#     print(f"Datum not periodic, enforcing it. V[0] : {volumes[0]}, V[-1] : {volumes[-1]}")
#     volumes[-1] = volumes[0] # ensure periodicity

# Set Reference Volume
V_ref = volumes[0]
print(f"Ref Volume: {V_ref:.2f}")

# --- PLOTTING ---
print("Plotting comparison...")
plt.figure(figsize=(10, 6))

# Plot Raw (Red Dots)
plt.plot(raw_times, raw_volumes, color='black', alpha=0.5, label='No periodicity')
plt.plot(times, volumes, color="red", alpha=0.8, label="Periodicity")

plt.legend()
plt.title(f"Volume Processing: {BASE_NAME}")
plt.xlabel("Time (s)")
plt.ylabel("Volume (mL)")
plt.grid(True, linestyle=':')
#plt.savefig(plot_sol_img, dpi=300)
plt.show()

# ==========================================
# 3. MESH SETUP
# ==========================================
print(f"--- Loading {MESH_FILE} ---")
# Meshio reads the coordinates EXACTLY as they are in the file.
# Since you exported the translated mesh, 'original_points' 
# are already in the correct translated position.
msh = meshio.read(MESH_FILE)
original_points = msh.points 

# --- AUTO-DETECT APEX LOGIC ---
# We assume the Apex is the bottom-most point (Minimum Z value).
# This works perfectly for the vertical prolate spheroid you generated.
min_z_index = np.argmin(original_points[:, 2]) # Find index of lowest Z
APEX_COORDS = original_points[min_z_index]     # Extract XYZ of that point

print(f"Auto-detected Apex at: {APEX_COORDS}")
print("This point will remain fixed (Displacement = 0).")

# Initialize VTK Objects
polydata = vtk.vtkPolyData()
vtk_pts = vtk.vtkPoints()
vtk_pts.SetData(numpy_support.numpy_to_vtk(original_points, deep=True))
polydata.SetPoints(vtk_pts)

# Add Cells (Topology)
if msh.cells:
    cells_list = [c.data for c in msh.cells if c.type in ["triangle", "quad"]]
    if cells_list:
        all_cells = np.vstack(cells_list)
        vtk_cells = vtk.vtkCellArray()
        for cell in all_cells:
            vtk_cells.InsertNextCell(len(cell), cell)
        polydata.SetPolys(vtk_cells)

# Pre-calculate vector from Apex (used for the vector model)
# Vector = Point - Apex
# This vector defines the direction of contraction.
vec_from_apex = original_points - APEX_COORDS

# ==========================================
# 4. PROCESSING LOOP
# ==========================================

if SAVE_MODE == "multiple":
    # --- MULTIPLE FILES MODE ---
    output_path = os.path.join(os.getcwd(), OUTPUT_DIR_NAME)
    os.makedirs(output_path, exist_ok=True)
    print(f"--- Mode: MULTIPLE. Saving frames to '{OUTPUT_DIR_NAME}/' ---")

    writer = vtk.vtkXMLPolyDataWriter()
    writer.SetInputData(polydata)

    for i, t in enumerate(times):
        V_t = volumes[i]
        
        # 1. Calc Factors
        S_t = np.cbrt(V_t / V_ref)
        g_t = S_t - 1.0
        
        # 2. Calc Displacement Vector
        # d = g * (x - Apex)
        displacement = g_t * vec_from_apex
        
        # 3. Deform Geometry (Physically move points)
        new_coords = original_points + displacement
        vtk_new_pts = numpy_support.numpy_to_vtk(new_coords, deep=True, array_type=vtk.VTK_DOUBLE)
        polydata.GetPoints().SetData(vtk_new_pts)
        
        # 4. ADD DATA ARRAYS
        # -- A. Displacement Vector
        vtk_disp = numpy_support.numpy_to_vtk(displacement, deep=True, array_type=vtk.VTK_DOUBLE)
        vtk_disp.SetName("Displacement") 
        polydata.GetPointData().SetVectors(vtk_disp)
        
        # -- B. Time Value
        time_array = vtk.vtkDoubleArray()
        time_array.SetName("TimeValue")
        time_array.SetNumberOfTuples(1)
        time_array.SetValue(0, t)
        polydata.GetFieldData().AddArray(time_array)

        # 5. Save Frame
        filename = os.path.join(output_path, f"frame_{i:04d}.vtp")
        writer.SetFileName(filename)
        writer.Write()
        
        if i % 20 == 0:
            print(f"Saved frame {i}/{len(times)}")

    print(f"Done. Open '{OUTPUT_DIR_NAME}/frame_....vtp' group in ParaView.")

else:
    # --- SINGLE FILE MODE ---
    print(f"--- Mode: SINGLE. Saving to '{OUTPUT_SINGLE_NAME}' ---")
    
    for i, t in enumerate(times):
        V_t = volumes[i]
        
        # 1. Calc Factors
        S_t = np.cbrt(V_t / V_ref)
        g_t = S_t - 1.0
        
        # 2. Calc Displacement Field
        displacement = g_t * vec_from_apex
        
        # 3. Add as Array
        vtk_disp = numpy_support.numpy_to_vtk(displacement, deep=True, array_type=vtk.VTK_DOUBLE)
        vtk_disp.SetName(f"displacement_{i:03d}")
        polydata.GetPointData().AddArray(vtk_disp)

        if i % 20 == 0:
            print(f"Processed step {i}/{len(times)}")

    # 4. Write Single File
    writer = vtk.vtkXMLPolyDataWriter()
    writer.SetFileName(OUTPUT_SINGLE_NAME)
    writer.SetInputData(polydata)
    writer.Write()
    print(f"Done. Use ParaView 'WarpByVector' to animate specific arrays.")